package net.ropyxa.roprer.misc;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.ropyxa.roprer.RopRer;
import net.ropyxa.roprer.block.RerMaterialsBlocks;
import net.ropyxa.roprer.item.RerMaterials;

import java.util.function.Supplier;

public class RerCrativeModeTabs {
	public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, RopRer.MOD_ID);

	 public static final Supplier<CreativeModeTab> RER_VANILLA_TAB = CREATIVE_MODE_TAB.register("rer_vanilla_tab",
				() -> CreativeModeTab.builder()
						  .icon(() -> new ItemStack(RerMaterials.TIN_INGOT.get()))
						  .title(Component.translatable("creativetab.rer_vanilla_tab"))
						  .displayItems((parameters, output) -> {
								output.accept(RerMaterialsBlocks.TIN_ORE);
						  }).build());

	public static final Supplier<CreativeModeTab> RER_MATERIALS_TAB = CREATIVE_MODE_TAB.register("rer_materials_tab",
			  () -> CreativeModeTab.builder()
						 .withTabsBefore(ResourceLocation.fromNamespaceAndPath(RopRer.MOD_ID, "rer_vanilla_tab"))
						 .icon(() -> new ItemStack(RerMaterials.TIN_INGOT.get()))
						 .title(Component.translatable("creativetab.rer_materials_tab"))
						 .displayItems((parameters, output) -> {
							  output.accept(RerMaterialsBlocks.TIN_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_TIN_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_TIN_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_TIN_ORE);
							  output.accept(RerMaterialsBlocks.RAW_TIN_BLOCK);
							  output.accept(RerMaterials.RAW_TIN);
							  output.accept(RerMaterialsBlocks.TIN_BLOCK);
							  output.accept(RerMaterials.TIN_INGOT);
							  output.accept(RerMaterials.TIN_NUGGET);

							  output.accept(RerMaterialsBlocks.COBALT_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_COBALT_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_COBALT_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_COBALT_ORE);
							  output.accept(RerMaterialsBlocks.RAW_COBALT_BLOCK);
							  output.accept(RerMaterials.RAW_COBALT);
							  output.accept(RerMaterialsBlocks.COBALT_BLOCK);
							  output.accept(RerMaterials.COBALT_INGOT);
							  output.accept(RerMaterials.COBALT_NUGGET);

							  output.accept(RerMaterialsBlocks.APATITE_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_APATITE_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_APATITE_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_APATITE_ORE);
							  output.accept(RerMaterialsBlocks.APATITE_CLUSTER_BLOCK);
							  output.accept(RerMaterials.APATITE_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.APATITE_BLOCK);
							  output.accept(RerMaterials.APATITE_GEM);
							  output.accept(RerMaterials.APATITE_FRAGMENT);

							  output.accept(RerMaterialsBlocks.CINNABAR_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_CINNABAR_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_CINNABAR_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_CINNABAR_ORE);
							  output.accept(RerMaterialsBlocks.CINNABAR_CLUSTER_BLOCK);
							  output.accept(RerMaterials.CINNABAR_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.CINNABAR_BLOCK);
							  output.accept(RerMaterials.CINNABAR_GEM);
							  output.accept(RerMaterials.CINNABAR_FRAGMENT);

							  output.accept(RerMaterialsBlocks.ALUMINUM_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_ALUMINUM_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_ALUMINUM_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_ALUMINUM_ORE);
							  output.accept(RerMaterialsBlocks.RAW_ALUMINUM_BLOCK);
							  output.accept(RerMaterials.RAW_ALUMINUM);
							  output.accept(RerMaterialsBlocks.ALUMINUM_BLOCK);
							  output.accept(RerMaterials.ALUMINUM_INGOT);
							  output.accept(RerMaterials.ALUMINUM_NUGGET);

							  output.accept(RerMaterialsBlocks.AQUITE_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_AQUITE_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_AQUITE_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_AQUITE_ORE);
							  output.accept(RerMaterialsBlocks.AQUITE_CLUSTER_BLOCK);
							  output.accept(RerMaterials.AQUITE_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.AQUITE_BLOCK);
							  output.accept(RerMaterials.AQUITE_GEM);
							  output.accept(RerMaterials.AQUITE_FRAGMENT);

							  output.accept(RerMaterialsBlocks.BITUMEN_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_BITUMEN_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_BITUMEN_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_BITUMEN_ORE);
							  output.accept(RerMaterialsBlocks.BITUMEN_CLUSTER_BLOCK);
							  output.accept(RerMaterials.BITUMEN_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.BITUMEN_BLOCK);
							  output.accept(RerMaterials.BITUMEN_GEM);
							  output.accept(RerMaterials.BITUMEN_FRAGMENT);

							  output.accept(RerMaterialsBlocks.ARCANE_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_ARCANE_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_ARCANE_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_ARCANE_ORE);
							  output.accept(RerMaterialsBlocks.ARCANE_CLUSTER_BLOCK);
							  output.accept(RerMaterials.ARCANE_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.ARCANE_BLOCK);
							  output.accept(RerMaterials.ARCANE_GEM);
							  output.accept(RerMaterials.ARCANE_FRAGMENT);

							  output.accept(RerMaterialsBlocks.IRIDIUM_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_IRIDIUM_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_IRIDIUM_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_IRIDIUM_ORE);
							  output.accept(RerMaterialsBlocks.RAW_IRIDIUM_BLOCK);
							  output.accept(RerMaterials.RAW_IRIDIUM);
							  output.accept(RerMaterialsBlocks.IRIDIUM_BLOCK);
							  output.accept(RerMaterials.IRIDIUM_INGOT);
							  output.accept(RerMaterials.IRIDIUM_NUGGET);

							  output.accept(RerMaterialsBlocks.LEAD_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_LEAD_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_LEAD_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_LEAD_ORE);
							  output.accept(RerMaterialsBlocks.RAW_LEAD_BLOCK);
							  output.accept(RerMaterials.RAW_LEAD);
							  output.accept(RerMaterialsBlocks.LEAD_BLOCK);
							  output.accept(RerMaterials.LEAD_INGOT);
							  output.accept(RerMaterials.LEAD_NUGGET);

							  output.accept(RerMaterialsBlocks.NICKEL_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_NICKEL_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_NICKEL_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_NICKEL_ORE);
							  output.accept(RerMaterialsBlocks.RAW_NICKEL_BLOCK);
							  output.accept(RerMaterials.RAW_NICKEL);
							  output.accept(RerMaterialsBlocks.NICKEL_BLOCK);
							  output.accept(RerMaterials.NICKEL_INGOT);
							  output.accept(RerMaterials.NICKEL_NUGGET);

							  output.accept(RerMaterialsBlocks.OSMIUM_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_OSMIUM_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_OSMIUM_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_OSMIUM_ORE);
							  output.accept(RerMaterialsBlocks.RAW_OSMIUM_BLOCK);
							  output.accept(RerMaterials.RAW_OSMIUM);
							  output.accept(RerMaterialsBlocks.OSMIUM_BLOCK);
							  output.accept(RerMaterials.OSMIUM_INGOT);
							  output.accept(RerMaterials.OSMIUM_NUGGET);

							  output.accept(RerMaterialsBlocks.CARMINITE_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_CARMINITE_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_CARMINITE_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_CARMINITE_ORE);
							  output.accept(RerMaterialsBlocks.CARMINITE_CLUSTER_BLOCK);
							  output.accept(RerMaterials.CARMINITE_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.CARMINITE_BLOCK);
							  output.accept(RerMaterials.CARMINITE_GEM);
							  output.accept(RerMaterials.CARMINITE_FRAGMENT);

							  output.accept(RerMaterialsBlocks.CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.CERTUS_QUARTZ_CLUSTER_BLOCK);
							  output.accept(RerMaterials.CERTUS_QUARTZ_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.CERTUS_QUARTZ_BLOCK);
							  output.accept(RerMaterials.CERTUS_QUARTZ_GEM);
							  output.accept(RerMaterials.CERTUS_QUARTZ_FRAGMENT);

							  output.accept(RerMaterialsBlocks.CHARGED_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_CHARGED_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_CHARGED_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_CHARGED_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterialsBlocks.CHARGED_CERTUS_QUARTZ_CLUSTER_BLOCK);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.CHARGED_CERTUS_QUARTZ_BLOCK);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_GEM);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_FRAGMENT);

							  output.accept(RerMaterialsBlocks.CHAROITE_ORE);
							  output.accept(RerMaterialsBlocks.NETHERRACK_CHAROITE_ORE);
							  output.accept(RerMaterialsBlocks.END_STONE_CHAROITE_ORE);
							  output.accept(RerMaterialsBlocks.DEEPSLATE_CHAROITE_ORE);
							  output.accept(RerMaterialsBlocks.CHAROITE_CLUSTER_BLOCK);
							  output.accept(RerMaterials.CHAROITE_CLUSTER_SHARD);
							  output.accept(RerMaterialsBlocks.CHAROITE_BLOCK);
							  output.accept(RerMaterials.CHAROITE_GEM);
							  output.accept(RerMaterials.CHAROITE_FRAGMENT);
						 }).build());

	public static final Supplier<CreativeModeTab> RER_DETAILS_TAB = CREATIVE_MODE_TAB.register("rer_details_tab",
			  () -> CreativeModeTab.builder()
						 .withTabsBefore(ResourceLocation.fromNamespaceAndPath(RopRer.MOD_ID, "rer_materials_tab"))
						 .icon(() -> new ItemStack(RerMaterials.TIN_GEAR.get()))
						 .title(Component.translatable("creativetab.rer_details_tab"))
						 .displayItems((parameters, output) -> {
							  output.accept(RerMaterials.TIN_PLATE);
							  output.accept(RerMaterials.TIN_LARGE_PLATE);
							  output.accept(RerMaterials.TIN_ROD);
							  output.accept(RerMaterials.TIN_WIRE);
							  output.accept(RerMaterials.TIN_GEAR);
							  output.accept(RerMaterials.TIN_DUST);
							  output.accept(RerMaterials.TIN_TINY_DUST);
							  output.accept(RerMaterials.TIN_RING);
							  output.accept(RerMaterials.TIN_BOLT);
							  output.accept(RerMaterials.TIN_DOUBLE_INGOT);
							  output.accept(RerMaterials.TIN_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_TIN_ORE);
							  output.accept(RerMaterials.TIN_CHUNK);
							  output.accept(RerMaterials.TIN_CLUSTER);
							  output.accept(RerMaterials.TIN_CRYSTAL);
							  output.accept(RerMaterials.TIN_SHARD);
							  output.accept(RerMaterials.TIN_CLUMP);
							  output.accept(RerMaterials.TIN_DIRTY_DUST);

							  output.accept(RerMaterials.COBALT_PLATE);
							  output.accept(RerMaterials.COBALT_LARGE_PLATE);
							  output.accept(RerMaterials.COBALT_ROD);
							  output.accept(RerMaterials.COBALT_WIRE);
							  output.accept(RerMaterials.COBALT_GEAR);
							  output.accept(RerMaterials.COBALT_DUST);
							  output.accept(RerMaterials.COBALT_TINY_DUST);
							  output.accept(RerMaterials.COBALT_RING);
							  output.accept(RerMaterials.COBALT_BOLT);
							  output.accept(RerMaterials.COBALT_DOUBLE_INGOT);
							  output.accept(RerMaterials.COBALT_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_COBALT_ORE);
							  output.accept(RerMaterials.COBALT_CHUNK);
							  output.accept(RerMaterials.COBALT_CLUSTER);
							  output.accept(RerMaterials.COBALT_CRYSTAL);
							  output.accept(RerMaterials.COBALT_SHARD);
							  output.accept(RerMaterials.COBALT_CLUMP);
							  output.accept(RerMaterials.COBALT_DIRTY_DUST);

							  output.accept(RerMaterials.APATITE_PLATE);
							  output.accept(RerMaterials.APATITE_LARGE_PLATE);
							  output.accept(RerMaterials.APATITE_ROD);
							  output.accept(RerMaterials.APATITE_WIRE);
							  output.accept(RerMaterials.APATITE_GEAR);
							  output.accept(RerMaterials.APATITE_DUST);
							  output.accept(RerMaterials.APATITE_TINY_DUST);
							  output.accept(RerMaterials.APATITE_RING);
							  output.accept(RerMaterials.APATITE_BOLT);
							  output.accept(RerMaterials.APATITE_DOUBLE_GEM);
							  output.accept(RerMaterials.APATITE_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_APATITE_ORE);
							  output.accept(RerMaterials.APATITE_CHUNK);
							  output.accept(RerMaterials.APATITE_CLUSTER);
							  output.accept(RerMaterials.APATITE_CRYSTAL);
							  output.accept(RerMaterials.APATITE_SHARD);
							  output.accept(RerMaterials.APATITE_CLUMP);
							  output.accept(RerMaterials.APATITE_DIRTY_DUST);

							  output.accept(RerMaterials.CINNABAR_PLATE);
							  output.accept(RerMaterials.CINNABAR_LARGE_PLATE);
							  output.accept(RerMaterials.CINNABAR_ROD);
							  output.accept(RerMaterials.CINNABAR_WIRE);
							  output.accept(RerMaterials.CINNABAR_GEAR);
							  output.accept(RerMaterials.CINNABAR_DUST);
							  output.accept(RerMaterials.CINNABAR_TINY_DUST);
							  output.accept(RerMaterials.CINNABAR_RING);
							  output.accept(RerMaterials.CINNABAR_BOLT);
							  output.accept(RerMaterials.CINNABAR_DOUBLE_GEM);
							  output.accept(RerMaterials.CINNABAR_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_CINNABAR_ORE);
							  output.accept(RerMaterials.CINNABAR_CHUNK);
							  output.accept(RerMaterials.CINNABAR_CLUSTER);
							  output.accept(RerMaterials.CINNABAR_CRYSTAL);
							  output.accept(RerMaterials.CINNABAR_SHARD);
							  output.accept(RerMaterials.CINNABAR_CLUMP);
							  output.accept(RerMaterials.CINNABAR_DIRTY_DUST);

							  output.accept(RerMaterials.ALUMINUM_PLATE);
							  output.accept(RerMaterials.ALUMINUM_LARGE_PLATE);
							  output.accept(RerMaterials.ALUMINUM_ROD);
							  output.accept(RerMaterials.ALUMINUM_WIRE);
							  output.accept(RerMaterials.ALUMINUM_GEAR);
							  output.accept(RerMaterials.ALUMINUM_DUST);
							  output.accept(RerMaterials.ALUMINUM_TINY_DUST);
							  output.accept(RerMaterials.ALUMINUM_RING);
							  output.accept(RerMaterials.ALUMINUM_BOLT);
							  output.accept(RerMaterials.ALUMINUM_DOUBLE_INGOT);
							  output.accept(RerMaterials.ALUMINUM_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_ALUMINUM_ORE);
							  output.accept(RerMaterials.ALUMINUM_CHUNK);
							  output.accept(RerMaterials.ALUMINUM_CLUSTER);
							  output.accept(RerMaterials.ALUMINUM_CRYSTAL);
							  output.accept(RerMaterials.ALUMINUM_SHARD);
							  output.accept(RerMaterials.ALUMINUM_CLUMP);
							  output.accept(RerMaterials.ALUMINUM_DIRTY_DUST);

							  output.accept(RerMaterials.AQUITE_PLATE);
							  output.accept(RerMaterials.AQUITE_LARGE_PLATE);
							  output.accept(RerMaterials.AQUITE_ROD);
							  output.accept(RerMaterials.AQUITE_WIRE);
							  output.accept(RerMaterials.AQUITE_GEAR);
							  output.accept(RerMaterials.AQUITE_DUST);
							  output.accept(RerMaterials.AQUITE_TINY_DUST);
							  output.accept(RerMaterials.AQUITE_RING);
							  output.accept(RerMaterials.AQUITE_BOLT);
							  output.accept(RerMaterials.AQUITE_DOUBLE_GEM);
							  output.accept(RerMaterials.AQUITE_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_AQUITE_ORE);
							  output.accept(RerMaterials.AQUITE_CHUNK);
							  output.accept(RerMaterials.AQUITE_CLUSTER);
							  output.accept(RerMaterials.AQUITE_CRYSTAL);
							  output.accept(RerMaterials.AQUITE_SHARD);
							  output.accept(RerMaterials.AQUITE_CLUMP);
							  output.accept(RerMaterials.AQUITE_DIRTY_DUST);

							  output.accept(RerMaterials.BITUMEN_PLATE);
							  output.accept(RerMaterials.BITUMEN_LARGE_PLATE);
							  output.accept(RerMaterials.BITUMEN_ROD);
							  output.accept(RerMaterials.BITUMEN_WIRE);
							  output.accept(RerMaterials.BITUMEN_GEAR);
							  output.accept(RerMaterials.BITUMEN_DUST);
							  output.accept(RerMaterials.BITUMEN_TINY_DUST);
							  output.accept(RerMaterials.BITUMEN_RING);
							  output.accept(RerMaterials.BITUMEN_BOLT);
							  output.accept(RerMaterials.BITUMEN_DOUBLE_GEM);
							  output.accept(RerMaterials.BITUMEN_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_BITUMEN_ORE);
							  output.accept(RerMaterials.BITUMEN_CHUNK);
							  output.accept(RerMaterials.BITUMEN_CLUSTER);
							  output.accept(RerMaterials.BITUMEN_CRYSTAL);
							  output.accept(RerMaterials.BITUMEN_SHARD);
							  output.accept(RerMaterials.BITUMEN_CLUMP);
							  output.accept(RerMaterials.BITUMEN_DIRTY_DUST);

							  output.accept(RerMaterials.ARCANE_PLATE);
							  output.accept(RerMaterials.ARCANE_LARGE_PLATE);
							  output.accept(RerMaterials.ARCANE_ROD);
							  output.accept(RerMaterials.ARCANE_WIRE);
							  output.accept(RerMaterials.ARCANE_GEAR);
							  output.accept(RerMaterials.ARCANE_DUST);
							  output.accept(RerMaterials.ARCANE_TINY_DUST);
							  output.accept(RerMaterials.ARCANE_RING);
							  output.accept(RerMaterials.ARCANE_BOLT);
							  output.accept(RerMaterials.ARCANE_DOUBLE_GEM);
							  output.accept(RerMaterials.ARCANE_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_ARCANE_ORE);
							  output.accept(RerMaterials.ARCANE_CHUNK);
							  output.accept(RerMaterials.ARCANE_CLUSTER);
							  output.accept(RerMaterials.ARCANE_CRYSTAL);
							  output.accept(RerMaterials.ARCANE_SHARD);
							  output.accept(RerMaterials.ARCANE_CLUMP);
							  output.accept(RerMaterials.ARCANE_DIRTY_DUST);

							  output.accept(RerMaterials.IRIDIUM_PLATE);
							  output.accept(RerMaterials.IRIDIUM_LARGE_PLATE);
							  output.accept(RerMaterials.IRIDIUM_ROD);
							  output.accept(RerMaterials.IRIDIUM_WIRE);
							  output.accept(RerMaterials.IRIDIUM_GEAR);
							  output.accept(RerMaterials.IRIDIUM_DUST);
							  output.accept(RerMaterials.IRIDIUM_TINY_DUST);
							  output.accept(RerMaterials.IRIDIUM_RING);
							  output.accept(RerMaterials.IRIDIUM_BOLT);
							  output.accept(RerMaterials.IRIDIUM_DOUBLE_INGOT);
							  output.accept(RerMaterials.IRIDIUM_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_IRIDIUM_ORE);
							  output.accept(RerMaterials.IRIDIUM_CHUNK);
							  output.accept(RerMaterials.IRIDIUM_CLUSTER);
							  output.accept(RerMaterials.IRIDIUM_CRYSTAL);
							  output.accept(RerMaterials.IRIDIUM_SHARD);
							  output.accept(RerMaterials.IRIDIUM_CLUMP);
							  output.accept(RerMaterials.IRIDIUM_DIRTY_DUST);

							  output.accept(RerMaterials.LEAD_PLATE);
							  output.accept(RerMaterials.LEAD_LARGE_PLATE);
							  output.accept(RerMaterials.LEAD_ROD);
							  output.accept(RerMaterials.LEAD_WIRE);
							  output.accept(RerMaterials.LEAD_GEAR);
							  output.accept(RerMaterials.LEAD_DUST);
							  output.accept(RerMaterials.LEAD_TINY_DUST);
							  output.accept(RerMaterials.LEAD_RING);
							  output.accept(RerMaterials.LEAD_BOLT);
							  output.accept(RerMaterials.LEAD_DOUBLE_INGOT);
							  output.accept(RerMaterials.LEAD_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_LEAD_ORE);
							  output.accept(RerMaterials.LEAD_CHUNK);
							  output.accept(RerMaterials.LEAD_CLUSTER);
							  output.accept(RerMaterials.LEAD_CRYSTAL);
							  output.accept(RerMaterials.LEAD_SHARD);
							  output.accept(RerMaterials.LEAD_CLUMP);
							  output.accept(RerMaterials.LEAD_DIRTY_DUST);

							  output.accept(RerMaterials.NICKEL_PLATE);
							  output.accept(RerMaterials.NICKEL_LARGE_PLATE);
							  output.accept(RerMaterials.NICKEL_ROD);
							  output.accept(RerMaterials.NICKEL_WIRE);
							  output.accept(RerMaterials.NICKEL_GEAR);
							  output.accept(RerMaterials.NICKEL_DUST);
							  output.accept(RerMaterials.NICKEL_TINY_DUST);
							  output.accept(RerMaterials.NICKEL_RING);
							  output.accept(RerMaterials.NICKEL_BOLT);
							  output.accept(RerMaterials.NICKEL_DOUBLE_INGOT);
							  output.accept(RerMaterials.NICKEL_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_NICKEL_ORE);
							  output.accept(RerMaterials.NICKEL_CHUNK);
							  output.accept(RerMaterials.NICKEL_CLUSTER);
							  output.accept(RerMaterials.NICKEL_CRYSTAL);
							  output.accept(RerMaterials.NICKEL_SHARD);
							  output.accept(RerMaterials.NICKEL_CLUMP);
							  output.accept(RerMaterials.NICKEL_DIRTY_DUST);

							  output.accept(RerMaterials.OSMIUM_PLATE);
							  output.accept(RerMaterials.OSMIUM_LARGE_PLATE);
							  output.accept(RerMaterials.OSMIUM_ROD);
							  output.accept(RerMaterials.OSMIUM_WIRE);
							  output.accept(RerMaterials.OSMIUM_GEAR);
							  output.accept(RerMaterials.OSMIUM_DUST);
							  output.accept(RerMaterials.OSMIUM_TINY_DUST);
							  output.accept(RerMaterials.OSMIUM_RING);
							  output.accept(RerMaterials.OSMIUM_BOLT);
							  output.accept(RerMaterials.OSMIUM_DOUBLE_INGOT);
							  output.accept(RerMaterials.OSMIUM_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_OSMIUM_ORE);
							  output.accept(RerMaterials.OSMIUM_CHUNK);
							  output.accept(RerMaterials.OSMIUM_CLUSTER);
							  output.accept(RerMaterials.OSMIUM_CRYSTAL);
							  output.accept(RerMaterials.OSMIUM_SHARD);
							  output.accept(RerMaterials.OSMIUM_CLUMP);
							  output.accept(RerMaterials.OSMIUM_DIRTY_DUST);

							  output.accept(RerMaterials.CARMINITE_PLATE);
							  output.accept(RerMaterials.CARMINITE_LARGE_PLATE);
							  output.accept(RerMaterials.CARMINITE_ROD);
							  output.accept(RerMaterials.CARMINITE_WIRE);
							  output.accept(RerMaterials.CARMINITE_GEAR);
							  output.accept(RerMaterials.CARMINITE_DUST);
							  output.accept(RerMaterials.CARMINITE_TINY_DUST);
							  output.accept(RerMaterials.CARMINITE_RING);
							  output.accept(RerMaterials.CARMINITE_BOLT);
							  output.accept(RerMaterials.CARMINITE_DOUBLE_GEM);
							  output.accept(RerMaterials.CARMINITE_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_CARMINITE_ORE);
							  output.accept(RerMaterials.CARMINITE_CHUNK);
							  output.accept(RerMaterials.CARMINITE_CLUSTER);
							  output.accept(RerMaterials.CARMINITE_CRYSTAL);
							  output.accept(RerMaterials.CARMINITE_SHARD);
							  output.accept(RerMaterials.CARMINITE_CLUMP);
							  output.accept(RerMaterials.CARMINITE_DIRTY_DUST);

							  output.accept(RerMaterials.CERTUS_QUARTZ_PLATE);
							  output.accept(RerMaterials.CERTUS_QUARTZ_LARGE_PLATE);
							  output.accept(RerMaterials.CERTUS_QUARTZ_ROD);
							  output.accept(RerMaterials.CERTUS_QUARTZ_WIRE);
							  output.accept(RerMaterials.CERTUS_QUARTZ_GEAR);
							  output.accept(RerMaterials.CERTUS_QUARTZ_DUST);
							  output.accept(RerMaterials.CERTUS_QUARTZ_TINY_DUST);
							  output.accept(RerMaterials.CERTUS_QUARTZ_RING);
							  output.accept(RerMaterials.CERTUS_QUARTZ_BOLT);
							  output.accept(RerMaterials.CERTUS_QUARTZ_DOUBLE_GEM);
							  output.accept(RerMaterials.CERTUS_QUARTZ_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterials.CERTUS_QUARTZ_CHUNK);
							  output.accept(RerMaterials.CERTUS_QUARTZ_CLUSTER);
							  output.accept(RerMaterials.CERTUS_QUARTZ_CRYSTAL);
							  output.accept(RerMaterials.CERTUS_QUARTZ_SHARD);
							  output.accept(RerMaterials.CERTUS_QUARTZ_CLUMP);
							  output.accept(RerMaterials.CERTUS_QUARTZ_DIRTY_DUST);

							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_PLATE);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_LARGE_PLATE);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_ROD);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_WIRE);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_GEAR);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_DUST);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_TINY_DUST);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_RING);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_BOLT);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_DOUBLE_GEM);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_CHARGED_CERTUS_QUARTZ_ORE);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_CHUNK);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_CLUSTER);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_CRYSTAL);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_SHARD);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_CLUMP);
							  output.accept(RerMaterials.CHARGED_CERTUS_QUARTZ_DIRTY_DUST);

							  output.accept(RerMaterials.CHAROITE_PLATE);
							  output.accept(RerMaterials.CHAROITE_LARGE_PLATE);
							  output.accept(RerMaterials.CHAROITE_ROD);
							  output.accept(RerMaterials.CHAROITE_WIRE);
							  output.accept(RerMaterials.CHAROITE_GEAR);
							  output.accept(RerMaterials.CHAROITE_DUST);
							  output.accept(RerMaterials.CHAROITE_TINY_DUST);
							  output.accept(RerMaterials.CHAROITE_RING);
							  output.accept(RerMaterials.CHAROITE_BOLT);
							  output.accept(RerMaterials.CHAROITE_DOUBLE_GEM);
							  output.accept(RerMaterials.CHAROITE_CURVED_PLATE);
							  output.accept(RerMaterials.CRUSHED_CHAROITE_ORE);
							  output.accept(RerMaterials.CHAROITE_CHUNK);
							  output.accept(RerMaterials.CHAROITE_CLUSTER);
							  output.accept(RerMaterials.CHAROITE_CRYSTAL);
							  output.accept(RerMaterials.CHAROITE_SHARD);
							  output.accept(RerMaterials.CHAROITE_CLUMP);
							  output.accept(RerMaterials.CHAROITE_DIRTY_DUST);
						 }).build());

	 public static final Supplier<CreativeModeTab> RER_ALLOYS_TAB = CREATIVE_MODE_TAB.register("rer_alloys_tab",
				() -> CreativeModeTab.builder()
						  .withTabsBefore(ResourceLocation.fromNamespaceAndPath(RopRer.MOD_ID, "rer_details_tab"))
						  .icon(() -> new ItemStack(RerMaterials.BRASS_INGOT.get()))
						  .title(Component.translatable("creativetab.rer_alloys_tab"))
						  .displayItems((parameters, output) -> {
								output.accept(RerMaterialsBlocks.BRASS_BLOCK);
								output.accept(RerMaterials.BRASS_INGOT);
								output.accept(RerMaterials.BRASS_NUGGET);
								output.accept(RerMaterials.BRASS_PLATE);
								output.accept(RerMaterials.BRASS_LARGE_PLATE);
								output.accept(RerMaterials.BRASS_ROD);
								output.accept(RerMaterials.BRASS_WIRE);
								output.accept(RerMaterials.BRASS_GEAR);
								output.accept(RerMaterials.BRASS_DUST);
								output.accept(RerMaterials.BRASS_TINY_DUST);
								output.accept(RerMaterials.BRASS_RING);
								output.accept(RerMaterials.BRASS_BOLT);
								output.accept(RerMaterials.BRASS_DOUBLE_INGOT);
								output.accept(RerMaterials.BRASS_CURVED_PLATE);
								output.accept(RerMaterials.BRASS_CHUNK);
								output.accept(RerMaterials.BRASS_CLUSTER);
								output.accept(RerMaterials.NOTHING1);
								output.accept(RerMaterials.NOTHING2);

								output.accept(RerMaterialsBlocks.BRONZE_BLOCK);
								output.accept(RerMaterials.BRONZE_INGOT);
								output.accept(RerMaterials.BRONZE_NUGGET);
								output.accept(RerMaterials.BRONZE_PLATE);
								output.accept(RerMaterials.BRONZE_LARGE_PLATE);
								output.accept(RerMaterials.BRONZE_ROD);
								output.accept(RerMaterials.BRONZE_WIRE);
								output.accept(RerMaterials.BRONZE_GEAR);
								output.accept(RerMaterials.BRONZE_DUST);
								output.accept(RerMaterials.BRONZE_TINY_DUST);
								output.accept(RerMaterials.BRONZE_RING);
								output.accept(RerMaterials.BRONZE_BOLT);
								output.accept(RerMaterials.BRONZE_DOUBLE_INGOT);
								output.accept(RerMaterials.BRONZE_CURVED_PLATE);
								output.accept(RerMaterials.BRONZE_CHUNK);
								output.accept(RerMaterials.BRONZE_CLUSTER);
								output.accept(RerMaterials.NOTHING3);
								output.accept(RerMaterials.NOTHING4);

								output.accept(RerMaterialsBlocks.CAST_IRON_BLOCK);
								output.accept(RerMaterials.CAST_IRON_INGOT);
								output.accept(RerMaterials.CAST_IRON_NUGGET);
								output.accept(RerMaterials.CAST_IRON_PLATE);
								output.accept(RerMaterials.CAST_IRON_LARGE_PLATE);
								output.accept(RerMaterials.CAST_IRON_ROD);
								output.accept(RerMaterials.CAST_IRON_WIRE);
								output.accept(RerMaterials.CAST_IRON_GEAR);
								output.accept(RerMaterials.CAST_IRON_DUST);
								output.accept(RerMaterials.CAST_IRON_TINY_DUST);
								output.accept(RerMaterials.CAST_IRON_RING);
								output.accept(RerMaterials.CAST_IRON_BOLT);
								output.accept(RerMaterials.CAST_IRON_DOUBLE_INGOT);
								output.accept(RerMaterials.CAST_IRON_CURVED_PLATE);
								output.accept(RerMaterials.CAST_IRON_CHUNK);
								output.accept(RerMaterials.CAST_IRON_CLUSTER);
								output.accept(RerMaterials.NOTHING5);
								output.accept(RerMaterials.NOTHING6);

								output.accept(RerMaterialsBlocks.SOUL_STEEL_BLOCK);
								output.accept(RerMaterials.SOUL_STEEL_INGOT);
								output.accept(RerMaterials.SOUL_STEEL_NUGGET);
								output.accept(RerMaterials.SOUL_STEEL_PLATE);
								output.accept(RerMaterials.SOUL_STEEL_LARGE_PLATE);
								output.accept(RerMaterials.SOUL_STEEL_ROD);
								output.accept(RerMaterials.SOUL_STEEL_WIRE);
								output.accept(RerMaterials.SOUL_STEEL_GEAR);
								output.accept(RerMaterials.SOUL_STEEL_DUST);
								output.accept(RerMaterials.SOUL_STEEL_TINY_DUST);
								output.accept(RerMaterials.SOUL_STEEL_RING);
								output.accept(RerMaterials.SOUL_STEEL_BOLT);
								output.accept(RerMaterials.SOUL_STEEL_DOUBLE_INGOT);
								output.accept(RerMaterials.SOUL_STEEL_CURVED_PLATE);
								output.accept(RerMaterials.SOUL_STEEL_CHUNK);
								output.accept(RerMaterials.SOUL_STEEL_CLUSTER);
								output.accept(RerMaterials.NOTHING7);
								output.accept(RerMaterials.NOTHING8);

								output.accept(RerMaterialsBlocks.STEEL_BLOCK);
								output.accept(RerMaterials.STEEL_INGOT);
								output.accept(RerMaterials.STEEL_NUGGET);
								output.accept(RerMaterials.STEEL_PLATE);
								output.accept(RerMaterials.STEEL_LARGE_PLATE);
								output.accept(RerMaterials.STEEL_ROD);
								output.accept(RerMaterials.STEEL_WIRE);
								output.accept(RerMaterials.STEEL_GEAR);
								output.accept(RerMaterials.STEEL_DUST);
								output.accept(RerMaterials.STEEL_TINY_DUST);
								output.accept(RerMaterials.STEEL_RING);
								output.accept(RerMaterials.STEEL_BOLT);
								output.accept(RerMaterials.STEEL_DOUBLE_INGOT);
								output.accept(RerMaterials.STEEL_CURVED_PLATE);
								output.accept(RerMaterials.STEEL_CHUNK);
								output.accept(RerMaterials.STEEL_CLUSTER);
								output.accept(RerMaterials.NOTHING9);
								output.accept(RerMaterials.NOTHING10);

								output.accept(RerMaterialsBlocks.ENDERIUM_BLOCK);
								output.accept(RerMaterials.ENDERIUM_INGOT);
								output.accept(RerMaterials.ENDERIUM_NUGGET);
								output.accept(RerMaterials.ENDERIUM_PLATE);
								output.accept(RerMaterials.ENDERIUM_LARGE_PLATE);
								output.accept(RerMaterials.ENDERIUM_ROD);
								output.accept(RerMaterials.ENDERIUM_WIRE);
								output.accept(RerMaterials.ENDERIUM_GEAR);
								output.accept(RerMaterials.ENDERIUM_DUST);
								output.accept(RerMaterials.ENDERIUM_TINY_DUST);
								output.accept(RerMaterials.ENDERIUM_RING);
								output.accept(RerMaterials.ENDERIUM_BOLT);
								output.accept(RerMaterials.ENDERIUM_DOUBLE_INGOT);
								output.accept(RerMaterials.ENDERIUM_CURVED_PLATE);
								output.accept(RerMaterials.ENDERIUM_CHUNK);
								output.accept(RerMaterials.ENDERIUM_CLUSTER);
								output.accept(RerMaterials.NOTHING11);
								output.accept(RerMaterials.NOTHING12);

								output.accept(RerMaterialsBlocks.ELECTRUM_BLOCK);
								output.accept(RerMaterials.ELECTRUM_INGOT);
								output.accept(RerMaterials.ELECTRUM_NUGGET);
								output.accept(RerMaterials.ELECTRUM_PLATE);
								output.accept(RerMaterials.ELECTRUM_LARGE_PLATE);
								output.accept(RerMaterials.ELECTRUM_ROD);
								output.accept(RerMaterials.ELECTRUM_WIRE);
								output.accept(RerMaterials.ELECTRUM_GEAR);
								output.accept(RerMaterials.ELECTRUM_DUST);
								output.accept(RerMaterials.ELECTRUM_TINY_DUST);
								output.accept(RerMaterials.ELECTRUM_RING);
								output.accept(RerMaterials.ELECTRUM_BOLT);
								output.accept(RerMaterials.ELECTRUM_DOUBLE_INGOT);
								output.accept(RerMaterials.ELECTRUM_CURVED_PLATE);
								output.accept(RerMaterials.ELECTRUM_CHUNK);
								output.accept(RerMaterials.ELECTRUM_CLUSTER);
								output.accept(RerMaterials.NOTHING13);
								output.accept(RerMaterials.NOTHING14);

								output.accept(RerMaterialsBlocks.LUMIUM_BLOCK);
								output.accept(RerMaterials.LUMIUM_INGOT);
								output.accept(RerMaterials.LUMIUM_NUGGET);
								output.accept(RerMaterials.LUMIUM_PLATE);
								output.accept(RerMaterials.LUMIUM_LARGE_PLATE);
								output.accept(RerMaterials.LUMIUM_ROD);
								output.accept(RerMaterials.LUMIUM_WIRE);
								output.accept(RerMaterials.LUMIUM_GEAR);
								output.accept(RerMaterials.LUMIUM_DUST);
								output.accept(RerMaterials.LUMIUM_TINY_DUST);
								output.accept(RerMaterials.LUMIUM_RING);
								output.accept(RerMaterials.LUMIUM_BOLT);
								output.accept(RerMaterials.LUMIUM_DOUBLE_INGOT);
								output.accept(RerMaterials.LUMIUM_CURVED_PLATE);
								output.accept(RerMaterials.LUMIUM_CHUNK);
								output.accept(RerMaterials.LUMIUM_CLUSTER);
								output.accept(RerMaterials.NOTHING15);
								output.accept(RerMaterials.NOTHING16);

								output.accept(RerMaterialsBlocks.FIERY_BLOCK);
								output.accept(RerMaterials.FIERY_INGOT);
								output.accept(RerMaterials.FIERY_NUGGET);
								output.accept(RerMaterials.FIERY_PLATE);
								output.accept(RerMaterials.FIERY_LARGE_PLATE);
								output.accept(RerMaterials.FIERY_ROD);
								output.accept(RerMaterials.FIERY_WIRE);
								output.accept(RerMaterials.FIERY_GEAR);
								output.accept(RerMaterials.FIERY_DUST);
								output.accept(RerMaterials.FIERY_TINY_DUST);
								output.accept(RerMaterials.FIERY_RING);
								output.accept(RerMaterials.FIERY_BOLT);
								output.accept(RerMaterials.FIERY_DOUBLE_INGOT);
								output.accept(RerMaterials.FIERY_CURVED_PLATE);
								output.accept(RerMaterials.FIERY_CHUNK);
								output.accept(RerMaterials.FIERY_CLUSTER);
								output.accept(RerMaterials.NOTHING17);
								output.accept(RerMaterials.NOTHING18);

								output.accept(RerMaterialsBlocks.SIGNALUM_BLOCK);
								output.accept(RerMaterials.SIGNALUM_INGOT);
								output.accept(RerMaterials.SIGNALUM_NUGGET);
								output.accept(RerMaterials.SIGNALUM_PLATE);
								output.accept(RerMaterials.SIGNALUM_LARGE_PLATE);
								output.accept(RerMaterials.SIGNALUM_ROD);
								output.accept(RerMaterials.SIGNALUM_WIRE);
								output.accept(RerMaterials.SIGNALUM_GEAR);
								output.accept(RerMaterials.SIGNALUM_DUST);
								output.accept(RerMaterials.SIGNALUM_TINY_DUST);
								output.accept(RerMaterials.SIGNALUM_RING);
								output.accept(RerMaterials.SIGNALUM_BOLT);
								output.accept(RerMaterials.SIGNALUM_DOUBLE_INGOT);
								output.accept(RerMaterials.SIGNALUM_CURVED_PLATE);
								output.accept(RerMaterials.SIGNALUM_CHUNK);
								output.accept(RerMaterials.SIGNALUM_CLUSTER);
								output.accept(RerMaterials.NOTHING19);
								output.accept(RerMaterials.NOTHING20);

								output.accept(RerMaterialsBlocks.INVAR_BLOCK);
								output.accept(RerMaterials.INVAR_INGOT);
								output.accept(RerMaterials.INVAR_NUGGET);
								output.accept(RerMaterials.INVAR_PLATE);
								output.accept(RerMaterials.INVAR_LARGE_PLATE);
								output.accept(RerMaterials.INVAR_ROD);
								output.accept(RerMaterials.INVAR_WIRE);
								output.accept(RerMaterials.INVAR_GEAR);
								output.accept(RerMaterials.INVAR_DUST);
								output.accept(RerMaterials.INVAR_TINY_DUST);
								output.accept(RerMaterials.INVAR_RING);
								output.accept(RerMaterials.INVAR_BOLT);
								output.accept(RerMaterials.INVAR_DOUBLE_INGOT);
								output.accept(RerMaterials.INVAR_CURVED_PLATE);
								output.accept(RerMaterials.INVAR_CHUNK);
								output.accept(RerMaterials.INVAR_CLUSTER);
								output.accept(RerMaterials.NOTHING21);
								output.accept(RerMaterials.NOTHING22);

								output.accept(RerMaterialsBlocks.GRAPHITE_BLOCK);
								output.accept(RerMaterials.GRAPHITE_INGOT);
								output.accept(RerMaterials.GRAPHITE_NUGGET);
								output.accept(RerMaterials.GRAPHITE_PLATE);
								output.accept(RerMaterials.GRAPHITE_LARGE_PLATE);
								output.accept(RerMaterials.GRAPHITE_ROD);
								output.accept(RerMaterials.GRAPHITE_WIRE);
								output.accept(RerMaterials.GRAPHITE_GEAR);
								output.accept(RerMaterials.GRAPHITE_DUST);
								output.accept(RerMaterials.GRAPHITE_TINY_DUST);
								output.accept(RerMaterials.GRAPHITE_RING);
								output.accept(RerMaterials.GRAPHITE_BOLT);
								output.accept(RerMaterials.GRAPHITE_DOUBLE_INGOT);
								output.accept(RerMaterials.GRAPHITE_CURVED_PLATE);
								output.accept(RerMaterials.GRAPHITE_CHUNK);
								output.accept(RerMaterials.GRAPHITE_CLUSTER);
								output.accept(RerMaterials.NOTHING23);
								output.accept(RerMaterials.NOTHING24);

								output.accept(RerMaterialsBlocks.CONSTANTAN_BLOCK);
								output.accept(RerMaterials.CONSTANTAN_INGOT);
								output.accept(RerMaterials.CONSTANTAN_NUGGET);
								output.accept(RerMaterials.CONSTANTAN_PLATE);
								output.accept(RerMaterials.CONSTANTAN_LARGE_PLATE);
								output.accept(RerMaterials.CONSTANTAN_ROD);
								output.accept(RerMaterials.CONSTANTAN_WIRE);
								output.accept(RerMaterials.CONSTANTAN_GEAR);
								output.accept(RerMaterials.CONSTANTAN_DUST);
								output.accept(RerMaterials.CONSTANTAN_TINY_DUST);
								output.accept(RerMaterials.CONSTANTAN_RING);
								output.accept(RerMaterials.CONSTANTAN_BOLT);
								output.accept(RerMaterials.CONSTANTAN_DOUBLE_INGOT);
								output.accept(RerMaterials.CONSTANTAN_CURVED_PLATE);
								output.accept(RerMaterials.CONSTANTAN_CHUNK);
								output.accept(RerMaterials.CONSTANTAN_CLUSTER);
								output.accept(RerMaterials.NOTHING25);
								output.accept(RerMaterials.NOTHING26);

								output.accept(RerMaterialsBlocks.REFINED_OBSIDIAN_BLOCK);
								output.accept(RerMaterials.REFINED_OBSIDIAN_INGOT);
								output.accept(RerMaterials.REFINED_OBSIDIAN_NUGGET);
								output.accept(RerMaterials.REFINED_OBSIDIAN_PLATE);
								output.accept(RerMaterials.REFINED_OBSIDIAN_LARGE_PLATE);
								output.accept(RerMaterials.REFINED_OBSIDIAN_ROD);
								output.accept(RerMaterials.REFINED_OBSIDIAN_WIRE);
								output.accept(RerMaterials.REFINED_OBSIDIAN_GEAR);
								output.accept(RerMaterials.REFINED_OBSIDIAN_DUST);
								output.accept(RerMaterials.REFINED_OBSIDIAN_TINY_DUST);
								output.accept(RerMaterials.REFINED_OBSIDIAN_RING);
								output.accept(RerMaterials.REFINED_OBSIDIAN_BOLT);
								output.accept(RerMaterials.REFINED_OBSIDIAN_DOUBLE_INGOT);
								output.accept(RerMaterials.REFINED_OBSIDIAN_CURVED_PLATE);
								output.accept(RerMaterials.REFINED_OBSIDIAN_CHUNK);
								output.accept(RerMaterials.REFINED_OBSIDIAN_CLUSTER);
								output.accept(RerMaterials.NOTHING27);
								output.accept(RerMaterials.NOTHING28);

								output.accept(RerMaterialsBlocks.REFINED_GLOWSTONE_BLOCK);
								output.accept(RerMaterials.REFINED_GLOWSTONE_INGOT);
								output.accept(RerMaterials.REFINED_GLOWSTONE_NUGGET);
								output.accept(RerMaterials.REFINED_GLOWSTONE_PLATE);
								output.accept(RerMaterials.REFINED_GLOWSTONE_LARGE_PLATE);
								output.accept(RerMaterials.REFINED_GLOWSTONE_ROD);
								output.accept(RerMaterials.REFINED_GLOWSTONE_WIRE);
								output.accept(RerMaterials.REFINED_GLOWSTONE_GEAR);
								output.accept(RerMaterials.REFINED_GLOWSTONE_DUST);
								output.accept(RerMaterials.REFINED_GLOWSTONE_TINY_DUST);
								output.accept(RerMaterials.REFINED_GLOWSTONE_RING);
								output.accept(RerMaterials.REFINED_GLOWSTONE_BOLT);
								output.accept(RerMaterials.REFINED_GLOWSTONE_DOUBLE_INGOT);
								output.accept(RerMaterials.REFINED_GLOWSTONE_CURVED_PLATE);
								output.accept(RerMaterials.REFINED_GLOWSTONE_CHUNK);
								output.accept(RerMaterials.REFINED_GLOWSTONE_CLUSTER);
								output.accept(RerMaterials.NOTHING29);
								output.accept(RerMaterials.NOTHING30);
								output.accept(RerMaterialsBlocks.ORICHALCUM_BLOCK);
								output.accept(RerMaterials.ORICHALCUM_INGOT);
								output.accept(RerMaterials.ORICHALCUM_NUGGET);
								output.accept(RerMaterials.ORICHALCUM_PLATE);
								output.accept(RerMaterials.ORICHALCUM_LARGE_PLATE);
								output.accept(RerMaterials.ORICHALCUM_ROD);
								output.accept(RerMaterials.ORICHALCUM_WIRE);
								output.accept(RerMaterials.ORICHALCUM_GEAR);
								output.accept(RerMaterials.ORICHALCUM_DUST);
								output.accept(RerMaterials.ORICHALCUM_TINY_DUST);
								output.accept(RerMaterials.ORICHALCUM_RING);
								output.accept(RerMaterials.ORICHALCUM_BOLT);
								output.accept(RerMaterials.ORICHALCUM_DOUBLE_INGOT);
								output.accept(RerMaterials.ORICHALCUM_CURVED_PLATE);
								output.accept(RerMaterials.ORICHALCUM_CHUNK);
								output.accept(RerMaterials.ORICHALCUM_CLUSTER);
								output.accept(RerMaterials.NOTHING31);
								output.accept(RerMaterials.NOTHING32);

								output.accept(RerMaterialsBlocks.ROSE_GOLD_BLOCK);
								output.accept(RerMaterials.ROSE_GOLD_INGOT);
								output.accept(RerMaterials.ROSE_GOLD_NUGGET);
								output.accept(RerMaterials.ROSE_GOLD_PLATE);
								output.accept(RerMaterials.ROSE_GOLD_LARGE_PLATE);
								output.accept(RerMaterials.ROSE_GOLD_ROD);
								output.accept(RerMaterials.ROSE_GOLD_WIRE);
								output.accept(RerMaterials.ROSE_GOLD_GEAR);
								output.accept(RerMaterials.ROSE_GOLD_DUST);
								output.accept(RerMaterials.ROSE_GOLD_TINY_DUST);
								output.accept(RerMaterials.ROSE_GOLD_RING);
								output.accept(RerMaterials.ROSE_GOLD_BOLT);
								output.accept(RerMaterials.ROSE_GOLD_DOUBLE_INGOT);
								output.accept(RerMaterials.ROSE_GOLD_CURVED_PLATE);
								output.accept(RerMaterials.ROSE_GOLD_CHUNK);
								output.accept(RerMaterials.ROSE_GOLD_CLUSTER);
								output.accept(RerMaterials.NOTHING33);
								output.accept(RerMaterials.NOTHING34);

								output.accept(RerMaterialsBlocks.KNIGHTMETAL_BLOCK);
								output.accept(RerMaterials.KNIGHTMETAL_INGOT);
								output.accept(RerMaterials.KNIGHTMETAL_NUGGET);
								output.accept(RerMaterials.KNIGHTMETAL_PLATE);
								output.accept(RerMaterials.KNIGHTMETAL_LARGE_PLATE);
								output.accept(RerMaterials.KNIGHTMETAL_ROD);
								output.accept(RerMaterials.KNIGHTMETAL_WIRE);
								output.accept(RerMaterials.KNIGHTMETAL_GEAR);
								output.accept(RerMaterials.KNIGHTMETAL_DUST);
								output.accept(RerMaterials.KNIGHTMETAL_TINY_DUST);
								output.accept(RerMaterials.KNIGHTMETAL_RING);
								output.accept(RerMaterials.KNIGHTMETAL_BOLT);
								output.accept(RerMaterials.KNIGHTMETAL_DOUBLE_INGOT);
								output.accept(RerMaterials.KNIGHTMETAL_CURVED_PLATE);
								output.accept(RerMaterials.KNIGHTMETAL_CHUNK);
								output.accept(RerMaterials.KNIGHTMETAL_CLUSTER);
								output.accept(RerMaterials.NOTHING35);
								output.accept(RerMaterials.NOTHING36);

								output.accept(RerMaterialsBlocks.SKY_BLOCK);
								output.accept(RerMaterials.SKY_INGOT);
								output.accept(RerMaterials.SKY_NUGGET);
								output.accept(RerMaterials.SKY_PLATE);
								output.accept(RerMaterials.SKY_LARGE_PLATE);
								output.accept(RerMaterials.SKY_ROD);
								output.accept(RerMaterials.SKY_WIRE);
								output.accept(RerMaterials.SKY_GEAR);
								output.accept(RerMaterials.SKY_DUST);
								output.accept(RerMaterials.SKY_TINY_DUST);
								output.accept(RerMaterials.SKY_RING);
								output.accept(RerMaterials.SKY_BOLT);
								output.accept(RerMaterials.SKY_DOUBLE_INGOT);
								output.accept(RerMaterials.SKY_CURVED_PLATE);
								output.accept(RerMaterials.SKY_CHUNK);
								output.accept(RerMaterials.SKY_CLUSTER);
								output.accept(RerMaterials.NOTHING37);
								output.accept(RerMaterials.NOTHING38);

								output.accept(RerMaterialsBlocks.IRONWOOD_BLOCK);
								output.accept(RerMaterials.IRONWOOD_INGOT);
								output.accept(RerMaterials.IRONWOOD_NUGGET);
								output.accept(RerMaterials.IRONWOOD_PLATE);
								output.accept(RerMaterials.IRONWOOD_LARGE_PLATE);
								output.accept(RerMaterials.IRONWOOD_ROD);
								output.accept(RerMaterials.IRONWOOD_WIRE);
								output.accept(RerMaterials.IRONWOOD_GEAR);
								output.accept(RerMaterials.IRONWOOD_DUST);
								output.accept(RerMaterials.IRONWOOD_TINY_DUST);
								output.accept(RerMaterials.IRONWOOD_RING);
								output.accept(RerMaterials.IRONWOOD_BOLT);
								output.accept(RerMaterials.IRONWOOD_DOUBLE_INGOT);
								output.accept(RerMaterials.IRONWOOD_CURVED_PLATE);
								output.accept(RerMaterials.IRONWOOD_CHUNK);
								output.accept(RerMaterials.IRONWOOD_CLUSTER);
								output.accept(RerMaterials.NOTHING39);
								output.accept(RerMaterials.NOTHING40);

								output.accept(RerMaterialsBlocks.TAINED_GOLD_BLOCK);
								output.accept(RerMaterials.TAINED_GOLD_INGOT);
								output.accept(RerMaterials.TAINED_GOLD_NUGGET);
								output.accept(RerMaterials.TAINED_GOLD_PLATE);
								output.accept(RerMaterials.TAINED_GOLD_LARGE_PLATE);
								output.accept(RerMaterials.TAINED_GOLD_ROD);
								output.accept(RerMaterials.TAINED_GOLD_WIRE);
								output.accept(RerMaterials.TAINED_GOLD_GEAR);
								output.accept(RerMaterials.TAINED_GOLD_DUST);
								output.accept(RerMaterials.TAINED_GOLD_TINY_DUST);
								output.accept(RerMaterials.TAINED_GOLD_RING);
								output.accept(RerMaterials.TAINED_GOLD_BOLT);
								output.accept(RerMaterials.TAINED_GOLD_DOUBLE_INGOT);
								output.accept(RerMaterials.TAINED_GOLD_CURVED_PLATE);
								output.accept(RerMaterials.TAINED_GOLD_CHUNK);
								output.accept(RerMaterials.TAINED_GOLD_CLUSTER);
								output.accept(RerMaterials.NOTHING41);
								output.accept(RerMaterials.NOTHING42);

								output.accept(RerMaterialsBlocks.INFUSED_IRON_BLOCK);
								output.accept(RerMaterials.INFUSED_IRON_INGOT);
								output.accept(RerMaterials.INFUSED_IRON_NUGGET);
								output.accept(RerMaterials.INFUSED_IRON_PLATE);
								output.accept(RerMaterials.INFUSED_IRON_LARGE_PLATE);
								output.accept(RerMaterials.INFUSED_IRON_ROD);
								output.accept(RerMaterials.INFUSED_IRON_WIRE);
								output.accept(RerMaterials.INFUSED_IRON_GEAR);
								output.accept(RerMaterials.INFUSED_IRON_DUST);
								output.accept(RerMaterials.INFUSED_IRON_TINY_DUST);
								output.accept(RerMaterials.INFUSED_IRON_RING);
								output.accept(RerMaterials.INFUSED_IRON_BOLT);
								output.accept(RerMaterials.INFUSED_IRON_DOUBLE_INGOT);
								output.accept(RerMaterials.INFUSED_IRON_CURVED_PLATE);
								output.accept(RerMaterials.INFUSED_IRON_CHUNK);
								output.accept(RerMaterials.INFUSED_IRON_CLUSTER);
								output.accept(RerMaterials.NOTHING43);
								output.accept(RerMaterials.NOTHING44);
						  }).build());



	public static void register(IEventBus eventBus) {
		CREATIVE_MODE_TAB.register(eventBus);
	}
}
